name: supermind-min
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=supermind
      - POSTGRES_PASSWORD=supermind_pw
      - POSTGRES_DB=supermind
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7
    restart: unless-stopped
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
    volumes: [redisdata:/data]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    restart: unless-stopped
    command: ["start-dev","--http-port=8080","--hostname-strict=false"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports: ["8080:8080"]

volumes:
  pgdata:
  redisdata:
